// lib/data/product_specs.dart
final List<MapEntry<String, String>> productSpecsMapping = [
  MapEntry('Thương hiệu', 'thuonghieu'),
  MapEntry('Hãng sản xuất', 'hangsanxuat'),
  MapEntry('Công suất', 'congsuat'),
  MapEntry('Kích cỡ màn hình', 'kichcomanhinhtivi'),
  MapEntry('Độ phân giải', 'dophangiai'),
  MapEntry('Phân loại', 'phanloai'),
  MapEntry('Hệ điều hành', 'hedieuhanhtivi'),
  MapEntry('Tiện ích', 'tienich'),
  MapEntry('Công nghệ', 'congnghe'),
  MapEntry('Loại máy', 'loaimay'),
  MapEntry('Kiểu dáng', 'kieudang'),
  MapEntry('CPU', 'cpu'),
  MapEntry('Mainboard', 'mainboard'),
  MapEntry('RAM', 'ram'),
  MapEntry('Ổ cứng', 'ocung'),
  MapEntry('Card đồ họa', 'carddohoa'),
  MapEntry('Nhu cầu', 'nhucau'),
  MapEntry('Kích cỡ màn hình', 'kichcomanhinh'),
  MapEntry('Tính năng đặc biệt', 'tinhnangdacbiet'),
  MapEntry('Hiệu năng và pin', 'hieunangvapin'),
  MapEntry('Camera', 'camera'),
  MapEntry('Bộ nhớ trong', 'bonhotrong'),
  MapEntry('Dung lượng Ram', 'dungluongram'),
  MapEntry('Tần số quét', 'tansoquet'),
  MapEntry('Chip xử lý', 'chipxuli'),
];
